### ISSUE TITLE
Steine sammeln

### ISSUE THREAD

**Issue by Carpantus** [Mmtrx/FS22_LimeMission#4]
Hallo es gibt zwar eine Mod um steine bei Pflug-Missionen zu sammeln, aber wenn die Mission Abgeschlossen ist wird das Feld in den Stein zustand vor dem sammeln zurück gesetzt. Ist es möglich eine Mod zu mache so wie Kalkmissionen nur für Steine ?

**Comment by Mmtrx** [comment]
Jo - Steine-Mission ist eins meiner nächsten Projekte..

Es gibt schon einen [thread ](https://github.com/Mmtrx/FS22_BetterContracts/issues/141) dazu, daher schließ ich dies hier mal
